// Generated by @knighted/css/generate-types
// Do not edit.

export const stableSelectors = {
  button: 'knighted-button',
} as const

export type KnightedCssStableSelectors = typeof stableSelectors
export type KnightedCssStableSelectorToken = keyof typeof stableSelectors

export default stableSelectors
